### ISSUE TITLE
Integrate freebase location lookup with entity tags

### ISSUE THREAD

**Issue by pviolette3** [gt-big-data/retina-entity-tagger#4]
Add the freebase calls to the current pipeline for entity extraction

**Comment by akhiaji** [comment]
I think we should transition away from freebase as it is no longer supported. Has someone sent the Bing team an email at partnerwithbing@microsoft.com to get access to their knowledge graph, or should I send an email.

**Comment by pviolette3** [comment]
On moving from Freebase: agreed. Freebase has a nice API, but it will be discontinued.

Let's use Wikidata, which is a good alternative. Wikidata contains all the data that freebase does, and more. I have added a file that searches for entities based on text, to set us up for the hack night.

On reaching out to Bing: I think it is unnecessary for the synonyms API, since wikidata supports this (mostly). If they have a good knowledge graph api, we can consider it, but Wikidata is free, and accessible now, so let's plan on using Wikidata.

**Comment by pviolette3** [comment]
Closing this issue, in favor of a new issue that corresponds to Wikidata.
